version: '3.9'

services:
  
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7777777
    ports:
      - 5432:5432
    volumes:
      - ./server/migrations/migrations_up.sql:/docker-entrypoint-initdb.d/migrations_up.sql
      - ./data:/var/lib/postgresql/data
    networks:
     - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d exachange_rates -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
