linters:
  enable-all: false
  disable:
    - structcheck
    - ifshort
    - scopelint
    - deadcode
    - maligned
    - exhaustivestruct
    - golint
    - interfacer
    - nosnakecase
    - varcheck
    - depguard

linters-settings:
  depguard:
    exclude:
      - github.com/jmoiron/sqlx
