linters:
  enable-all: false
  disable:
    - structcheck
    - ifshort
    - scopelint
    - deadcode
    - maligned
    - exhaustivestruct
    - golint
    - interfacer
    - nosnakecase
    - varcheck
    - depguard
    - lll


